{
 "title": "Meteo Italia",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Kanton",
    "label": "Regione",
    "query": "select canton  from  weather_data where dt> now() - interval 2 hour and (country = \"IT\" or country=\"VA\") "
   },
   {
    "name": "Ort",
    "label": "luogo",
    "query": "select distinct city from  weather_data  where (dt> now() - interval 2 hour)  and canton=\"$Kanton\""
   }
  ]
 },
 "panels": [
  { "title": "Aktuelle Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  temperature as \"°C\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 35 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Temp. di condensazione",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  DewPoint(temperature, humidity) as \"Taupunkt\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\"\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "umidità",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  humidity as \"%\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\"\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "pressione",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  pressure as \"hPa\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 75 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Precipitazioni",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  rain_down_1h as \"mm\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" \norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Sole",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  100-clouds as \"%\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 75 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Vento Ø",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  wind_speed*3.6 as \"km/h\"  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 75 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  city as luogo, canton as regione, temperature as \"°C\", pressure as mBar, humidity as umidità,\n wind_direction as \"Direzione vento\", DATE_FORMAT(dt,\"%Hh%i:%ss\") as misura  from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and (time_inserted ) > now() -interval 180 MINUTE\norder by dt desc\nlimit 3\n\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 15, "y": 7 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select \n    weather_main as cielo,\n    CASE\n        WHEN wind_direction >= 337.5 OR wind_direction < 22.5 THEN 'Nord'\n        WHEN wind_direction >= 22.5 AND wind_direction < 67.5 THEN 'Nordest'\n        WHEN wind_direction >= 67.5 AND wind_direction < 112.5 THEN 'Est'\n        WHEN wind_direction >= 112.5 AND wind_direction < 157.5 THEN 'Sudest'\n        WHEN wind_direction >= 157.5 AND wind_direction < 202.5 THEN 'Sud'\n        WHEN wind_direction >= 202.5 AND wind_direction < 247.5 THEN 'Südovest'\n        WHEN wind_direction >= 247.5 AND wind_direction < 292.5 THEN 'Ovest'\n        WHEN wind_direction >= 292.5 AND wind_direction < 337.5 THEN 'Nordovest'\n    END as direzione from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and dt> now() - INTERVAL 75 MINUTE\norder by dt desc\nlimit 1"
    }
   ]
  },
  { "title": "Verlauf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  temperature as Mittel, \n        temperature_min as Min,\n        temperature_max as Max,\n        dewpoint(temperature,humidity) as Taupunkt,\n        DATE_sub(dt, INTERVAL 2 HOUR) as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(dt) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Umidità",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  humidity as umidità, \n        (dt - interval 2 hour) as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(dt) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Pressione",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  pressure as pressione, \n        time_inserted - interval 2 hour as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Sole",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  100-clouds as Sole, \n        time_inserted -interval 2 hour as Zeit from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Precipitazioni",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  rain_down_1h as Precipitazioni, \n        time_inserted - interval 2 hour as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Vento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  wind_speed*3.6 as vento, \n        time_inserted - interval 2 hour as time from weather_data \n where canton=\"$Kanton\" and city = \"$Ort\" and $__timeFilter(time_inserted) \nORDER BY time_inserted\n"
    }
   ]
  },
  {
   "title": "Clicca sulla colonna per vedere valori estremi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "valori estremi",
   "type": "table",
   "description": "sort by column clicking on the column by which you want to sort",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  city as luogo, canton as regione, temperature as Temp, humidity as \"umidità\", wind_speed*3.6 as vento, rain_down_1h as precipitazioni, \n        DATE_FORMAT(dt, '%H:%i') as ora\n        from weather_data \nwhere (dt + interval 30 minute )  > now() and (country= \"IT\" or country =\"VA\")\nORDER BY temperature\n\n"
    }
   ]
  }
 ]
}