{
 "title": "Wetter Österreich",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Bundesland",
    "query": "select distinct state from WetterÖsterreich where weather_timestamp> now() - interval 2 hour"
   },
   {
    "name": "Ort",
    "query": "select  distinct location from WetterÖsterreich\nwhere (state=\"$Bundesland\") and (weather_timestamp > now()- interval 2 hour)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  altitude as Höhe, location as Ort, state as Land, temperature as \"°C\", airpressure as mBar, airpressure_trend as Trend,\n wind_direction as \"W.Richtung\", weather_time as Zeit from WetterÖsterreich \n where state=\"$Bundesland\" and location = \"$Ort\"\norder by weather_time desc\nlimit 5"
    }
   ]
  },
  { "title": "Aktuelle Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Temperatur",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select temperature as Temperatur\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1 hour)\norder by weather_timestamp desc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select dewpoint(temperature,humidity) as Taupunkt\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1 hour)\norder by weather_timestamp desc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Feuchte",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  humidity as Feucht\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1 hour)\norder by weather_timestamp desc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Druck",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  airpressure as Druck\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 2 hour)\norder by weather_timestamp desc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Niederschlag",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  raindown as Niederschlag\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 2 hour)\norder by weather_timestamp desc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Sonne",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select sun, weather_time, weather_timestamp \nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1 hour)\norder by weather_timestamp desc\nlimit 1\n "
    }
   ]
  },
  {
   "title": "Wind Ø",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  wind_speed as Wind\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1.5 hour)\norder by weather_timestamp asc\nLimit 1\n "
    }
   ]
  },
  {
   "title": "Böen",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select  windpeak as Wind\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and weather_time> (now() - interval 1.5 hour)\norder by weather_timestamp asc\nLimit 1\n "
    }
   ]
  },
  { "title": "Verlauf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Temperatur und Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select temperature, DewPoint(temperature,humidity), weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \n\n"
    }
   ]
  },
  {
   "title": "Feuchte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select humidity,weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \nORDER BY temperature\n"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select airpressure,weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \nORDER BY temperature\n"
    }
   ]
  },
  {
   "title": "Sonne",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select sun,weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \nORDER BY temperature\n"
    }
   ]
  },
  {
   "title": "Niederschlag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select raindown,weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \nORDER BY temperature\n"
    }
   ]
  },
  {
   "title": "Wind ø und Böen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select wind_speed, windpeak,weather_time\nfrom WetterÖsterreich\nwhere state = \"$Bundesland\" and location= \"$Ort\" and $__timeFilter(weather_time) \nORDER BY temperature\n"
    }
   ]
  },
  {
   "title": "Extremwerte Klicken sie auf die Spalte nach der Sie sortieren wollen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Extremwerte",
   "type": "table",
   "description": "sort by column clicking on the column by which you want to sort",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "WetterCDN",
     "rawSql": "select distinct altitude as Höhe, location as \"Ort\", temperature as Temp, wind_speed as Wind, \nwindpeak as Böen, raindown as Niederschlag,DATE_FORMAT(weather_time + interval 1 hour, '%H:%i') as Zeit from WetterCDN.WetterÖsterreich \nwhere weather_time > now() -interval 1 hour\norder by Temp asc\n"
    }
   ]
  }
 ]
}